# Start from the official Jenkins LTS image
FROM jenkins/jenkins:lts

# Skip the initial setup wizard
ENV JAVA_OPTS="-Djenkins.install.runSetupWizard=false -Dhudson.security.csrf.GlobalCrumbIssuerConfiguration.DISABLE_CSRF_PROTECTION=true"

# Tell JCasC where to find the configuration file
ENV CASC_JENKINS_CONFIG="/var/jenkins_home/casc_configs/casc.yaml"

# Pre-install the required plugins using the Jenkins CLI tool
# workflow-aggregator pulls in the standard Pipeline plugins
RUN jenkins-plugin-cli --plugins configuration-as-code docker-workflow kubernetes-cli workflow-aggregator git job-dsl

RUN echo "-----------------------------------------------------------"

# # Copy our configuration file into the container
COPY casc.yaml /var/jenkins_home/casc_configs/casc.yaml

COPY helloworld-jobs.groovy /var/jenkins_home/dsl/helloworld-jobs.groovy
COPY application-jobs.groovy /var/jenkins_home/dsl/application-jobs.groovy
# COPY Jenkinsfile /project